files:
  include: '**/*.s+(a|c)ss'

options:
  formatter: stylish
  merge-default-rules: false

rules:
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: long
  id-name-format:
    - 1
    - convention: hyphenatedlowercase
  indentation:
    - 1
    - size: 4
  leading-zero:
    - 1
    - include: true
  placeholder-name-format:
    - 1
    - convention: hyphenatedlowercase
  property-sort-order:
    - 1
    - order: concentric
  space-before-brace: 1
  space-between-parens:
    - 1
    - include: true
